INSERT INTO APP.SALA (ID_SALA, DESCRIZIONE) VALUES (1, 'Sala 1');
INSERT INTO APP.SALA (ID_SALA, DESCRIZIONE) VALUES (2, 'Sala 2');
INSERT INTO APP.SALA (ID_SALA, DESCRIZIONE) VALUES (3, 'Sala 3');
INSERT INTO APP.SALA (ID_SALA, DESCRIZIONE) VALUES (4, 'Sala 4');
INSERT INTO APP.SALA (ID_SALA, DESCRIZIONE) VALUES (5, 'Sala 5');